name: train_eganet_x4
model_type: SRModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: DIV2K_train_HR_sub
    dataroot_lq: DIV2K_X4_sub

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # --- validation
  val_0:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: Set5/HRmod4
    dataroot_lq: Set5/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: Set14/HRmod4
    dataroot_lq: Set14/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: BSDS100
    type: PairedImageDataset
    dataroot_gt: BSDS100/HRmod4
    dataroot_lq: BSDS100/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: Urban100/HRmod4
    dataroot_lq: Urban100/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: Manga109/HRmod4
    dataroot_lq: Manga109/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk

network_g:
  type: EGANet
  upscale: 4
  in_chans: 3
  dim: 48
  groups: 3
  blocks: 3
  num_heads: 6
  kernel_size: 7
  ffn_ratio: 2.
  tlc_flag: true
  tlc_kernel: 48
  body_norm: false
  img_range: 1.
  upsampler: 'pixelshuffledirect'

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 2000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  # wandb:
  #   project: DLGSANet4SR
  #   resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500